name: Update lock files

on:
  workflow_dispatch:

jobs:
  release:
    name: Update lock files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: debug
        run: |
          git remote -v
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Update lock files
        run: |
          pip install -r requirements.txt
      - name: Test
        run: |
          pytest 
